sonar.sources=app/src/main/java,app/src/modern/java,app/src/legacy/java
sonar.tests=app/src/test/java
sonar.exclusions=app/src/main/cpp/**,app/src/main/resources/**,app/src/*/resources/**,**/build/**
sonar.java.source=17
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoModernDebugUnitTestReport/jacocoModernDebugUnitTestReport.xml
sonar.java.binaries=app/build/intermediates/javac/modernDebug/compileModernDebugJavaWithJavac/classes,app/build/intermediates/built_in_kotlinc/modernDebug/compileModernDebugKotlin/classes
sonar.java.test.binaries=app/build/intermediates/javac/modernDebugUnitTest/compileModernDebugUnitTestJavaWithJavac/classes,app/build/intermediates/built_in_kotlinc/modernDebugUnitTest/compileModernDebugUnitTestKotlin/classes
