[versions]
agp = "9.2.1"
kotlin = "2.3.20"
composeBom = "2026.06.01"
composeMaterial3 = "1.5.0-alpha23"
wearComposeMaterial3 = "1.6.2"
activity = "1.10.1"
xposed-api = "102.0.0"
xposed-service = "101.0.0"
xposed-legacy-api = "82"
dexkit = "2.2.0"
junit4 = "4.13.2"
appcompat = "1.7.1"
recyclerview = "1.4.0"
material = "1.13.0"
annotation = "1.10.0"
markwon = "4.6.2"
aboutLibraries = "14.2.1"
androidxTestExtJunit = "1.3.0"
androidxTestCore = "1.7.0"
baselineProfile = "1.5.0-alpha07"
uiautomator = "2.3.0"
materialKolor = "5.0.0-alpha07"
reorderable = "3.1.0"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
agp-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineProfile" }

[libraries]
libxposed-api = { group = "io.github.libxposed", name = "api", version.ref = "xposed-api" }
libxposed-service = { group = "io.github.libxposed", name = "service", version.ref = "xposed-service" }
legacy-xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed-legacy-api" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
markwon-core = { group = "io.noties.markwon", name = "core", version.ref = "markwon" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
wear-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "wearComposeMaterial3" }
wear-compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "wearComposeMaterial3" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestCore" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "baselineProfile" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
