package com.dpis.module.updates

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import com.dpis.module.SourceSmokeTestPaths

class UpdatePromptDialogCoordinatorSourceSmokeTest {
    @Test
    fun coordinatorUsesRootOwnedDisclaimerAndSharedUpdatePrompt() {
        val source = read("src/main/java/com/dpis/module/updates/UpdatePromptDialogCoordinator.kt")
        val dialogSource = read("src/main/java/com/dpis/module/updates/UpdateAvailableDialog.kt")
        val textInteropSource = read("src/main/java/com/dpis/module/ui/presentation/interop/AndroidTextInterop.kt")
        val disclaimerSource = read("src/main/java/com/dpis/module/ui/dialog/StartupDisclaimerDialog.kt")
        val modalSource = read("src/main/java/com/dpis/module/ui/dialog/ModalDialog.kt")
        val shellHostSource = read("src/main/java/com/dpis/module/MainComposeShellHost.kt")

        assertTrue(source.contains("class UpdatePromptDialogCoordinator"))
        assertTrue(source.contains("fun maybeShowStartupDisclaimerDialog("))
        assertTrue(source.contains("fun showUpdateAvailableDialog("))
        assertTrue(source.contains("StartupDisclaimerGate.show("))
        assertFalse(source.contains("StartupDisclaimerDialog.show("))
        assertFalse(source.contains("R.layout.dialog_startup_disclaimer"))
        assertTrue(disclaimerSource.contains("fun StartupDisclaimerDialog("))
        assertTrue(disclaimerSource.contains("rememberSaveable"))
        assertTrue(disclaimerSource.contains("dismissOnClickOutside = false"))
        assertTrue(disclaimerSource.contains("dismissOnBackPress = false"))
        assertTrue(disclaimerSource.contains("BackHandler(onBack = onBack)"))
        assertTrue(disclaimerSource.contains("color = MaterialTheme.colorScheme.onSurface"))
        assertFalse(disclaimerSource.contains("MaterialAlertDialogBuilder"))
        assertFalse(disclaimerSource.contains("ComposeView"))
        assertTrue(modalSource.contains("fun StructuredModalDialog("))
        assertTrue(modalSource.contains("usePlatformDefaultWidth = false"))
        assertTrue(modalSource.contains(".widthIn(max = 560.dp)"))
        assertTrue(modalSource.contains(".heightIn(max = maxHeight)"))
        assertTrue(modalSource.contains(".imeWindowPan(imeFocusBoundary)"))
        assertFalse(modalSource.contains("val minHeight"))
        assertTrue(modalSource.contains(".weight(1f, fill = false)"))
        assertTrue(modalSource.contains(".verticalScroll(rememberScrollState())"))
        assertTrue(shellHostSource.contains("fun showStartupDisclaimer("))
        assertTrue(shellHostSource.contains("startupDisclaimer = null"))
        assertTrue(shellHostSource.contains("StartupDisclaimerDialog("))
        assertTrue(shellHostSource.contains("DisposableEffect(disclaimerPresenter)"))
        assertTrue(disclaimerSource
            .contains("presentedBy"))
        assertTrue(source.contains("interface StartupDisclaimerAcceptance"))
        assertTrue(source.contains("acceptance.isAccepted()"))
        assertTrue(source.contains("acceptance.markAccepted()"))
        assertFalse(source.contains("StartupDisclaimerStore"))
        assertTrue(source.contains("UpdateAvailableDialog.create("))
        assertTrue(source.contains("fun applyLargeDialogWidth(dialog: AlertDialog)"))
        assertTrue(source.contains("host.applyLargeDialogWidth(dialogHandle.dialog)"))
        assertFalse(source.contains("DialogWindowSizer"))
        assertTrue(source.contains("dialogHandle.setCancel("))
        assertTrue(source.contains("if (host.isDownloadInProgress())"))
        val cancelStart = source.indexOf("dialogHandle.setCancel(")
        val cancelEnd = source.indexOf("        )", cancelStart)
        assertTrue(cancelStart >= 0)
        assertTrue(cancelEnd > cancelStart)
        assertFalse(source.substring(cancelStart, cancelEnd).contains("host.markPromptedVersion(request.versionCode)"))
        assertTrue(source.contains("host.markPromptedVersion(request.versionCode)"))
        assertTrue(source.contains("startStartupUpdateDownload("))
        assertTrue(source.contains("request: UpdatePromptRequest"))
        assertTrue(source.contains("host.onUpdatePromptDismissed()"))
        assertTrue(source.contains("!activity.isChangingConfigurations"))
        assertTrue(source.contains("private val releaseNotesController: ReleaseNotesController"))
        assertTrue(source.contains("releaseNotesController.load("))
        assertTrue(source.contains("dialogHandle.isShowing()"))
        assertTrue(source.contains("R.string.about_update_release_notes_loading"))
        assertTrue(source.contains("ReleaseNotesMarkdownRenderer.render("))
        assertTrue(dialogSource.contains("AnimatedVisibility(expanded)"))
        assertTrue(dialogSource.contains("BoxWithConstraints(Modifier.fillMaxWidth())"))
        assertTrue(dialogSource.contains("val compactActionRow = maxWidth < 420.dp"))
        assertTrue(dialogSource.contains("modifier = Modifier.fillMaxWidth()"))
        assertTrue(dialogSource.contains("Row("))
        assertTrue(dialogSource.contains("RoundedCornerShape(16.dp)"))
        assertFalse(dialogSource.contains("painterResource"))
        assertTrue(source.contains("request.versionName"))
        assertTrue(source.contains("request.versionCode"))
        assertTrue(dialogSource.contains("toComposeAnnotatedString()"))
        assertTrue(textInteropSource.contains("addLink(LinkAnnotation.Url(span.url)"))
    }

    private fun read(relativePath: String): String = SourceSmokeTestPaths.read(relativePath)
}
